### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by anthrolisp** [gera2ld/marktiddly#1] opened 2023-03-07 15:17 UTC
how to install this package? thanks in advance!

**Comment by gera2ld** [comment] 2023-03-08 13:12
Assuming you have Node.js installed.

You don't need to install it, just run the command to generate an HTML:

```bash
npx marktiddly generate --cwd path/to/your/markdown_dir -o output.html
```

Then you can open the HTML (`output.html` here) with any modern browser.

**Comment by anthrolisp** [comment] 2023-03-08 18:20
I have npm and nodesjs installed (on Ubuntu). When I download and cd into the marktiddly package, and type the command above I get the following out put:

/Downloads/marktiddly-main$ npx marktiddly generate --cwd demo -o output.html
sh: 1: marktiddly: not found

Any thoughts? Thanks in advance!

**Comment by gera2ld** [comment] 2023-03-09 04:29
Looks like the command-line is broken, I'll fix it later. Thanks for the report.

**Comment by gera2ld** [comment] 2023-03-09 13:06
Fixed in v0.1.2.

**Closed as completed by gera2ld** 2023-03-09 13:06 UTC
Labels: question

**Comment by anthrolisp** [comment] 2023-03-09 13:21
Just tested, and seem to be getting the same error:

:~/Downloads/marktiddly-0.1.2$ npx marktiddly serve --cwd demo --default-open marktiddly
sh: 1: marktiddly: not found

Thank you in advance!!
I've very excited to try this for my projects!

**Comment by gera2ld** [comment] 2023-03-09 14:15
Hmm, that's weird, can you share the Node.js version info?

```bash
$ node -v
$ npm -v
```

And maybe also try if `npx` works for other tools:

```bash
$ npx cowsay hi
```

**Comment by anthrolisp** [comment] 2023-03-09 14:18
$ node -v
v18.7.0
$ npm -v
8.18.0
$ npx cowsay hi
Need to install the following packages:
  cowsay@1.5.0
Ok to proceed? (y) y
 ____
< hi >
 ----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by gera2ld** [comment] 2023-03-09 14:29
I tried different node versions on my macOS and Linux server but still cannot reproduce it.

~~Could you make sure you are running the latest version?~~

```bash
$ npx marktiddly --version
> 0.1.2
```

If it's an old version you might need to purge the cache first:

```bash
$ rm -rf ~/.npm/_npx
```

Just realized that the command-line may not work for you at all. Maybe you can try `npx marktiddly@0.1.2 ...` instead.
